### PR TITLE
Test pytest-operator changes

### PR DESCRIPTION
**Pull request by addyess**

### CODE REVIEW

**Comment by addyess** [comment]
@claudiubelu any chance you could see if this resolves the integration test issues?

**Comment by claudiubelu** [comment]
> @claudiubelu any chance you could see if this resolves the integration test issues?

It seems that there's a conflict that needs to be resolved. Once that's fixed, we should see the integration tests if they're passing or not.

**Comment by addyess** [comment]
@claudiubelu now?

**Comment by addyess** [comment]
FYI -- this is a draft PR not intended to be merged -- only intended to test is pytest-operator is functioning for this project

**Comment by addyess** [comment]
`0.18.0` of pytest-operator has been published.  Closing

**Pull request closed without merging**
